// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbVQQwjXMtgX9HIavyyT_HREfRcOgBnqo',
    appId: '1:920016786759:web:30be58f074e2be1d6ce862',
    messagingSenderId: '920016786759',
    projectId: 'projectt9-e1cc4',
    authDomain: 'projectt9-e1cc4.firebaseapp.com',
    storageBucket: 'projectt9-e1cc4.firebasestorage.app',
    measurementId: 'G-YCDNEPY263',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb22kejuoPgNuONnX-taN2G4JJ34RnFcg',
    appId: '1:920016786759:android:caa400f7d64104c46ce862',
    messagingSenderId: '920016786759',
    projectId: 'projectt9-e1cc4',
    storageBucket: 'projectt9-e1cc4.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjA7DPB7LLsv2lR6s-mNy6WGwJk0jsRKA',
    appId: '1:920016786759:ios:b43fe39df30933b46ce862',
    messagingSenderId: '920016786759',
    projectId: 'projectt9-e1cc4',
    storageBucket: 'projectt9-e1cc4.firebasestorage.app',
    iosBundleId: '22312141',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjA7DPB7LLsv2lR6s-mNy6WGwJk0jsRKA',
    appId: '1:920016786759:ios:b43fe39df30933b46ce862',
    messagingSenderId: '920016786759',
    projectId: 'projectt9-e1cc4',
    storageBucket: 'projectt9-e1cc4.firebasestorage.app',
    iosBundleId: '22312141',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbVQQwjXMtgX9HIavyyT_HREfRcOgBnqo',
    appId: '1:920016786759:web:68c0a070cdc83f176ce862',
    messagingSenderId: '920016786759',
    projectId: 'projectt9-e1cc4',
    authDomain: 'projectt9-e1cc4.firebaseapp.com',
    storageBucket: 'projectt9-e1cc4.firebasestorage.app',
    measurementId: 'G-469ZBYWNHF',
  );

}